import archiver from 'archiver'
import { Readable } from 'node:stream'
import { uploadBufferWithKey } from '@omniply/shared'
import { buildHtmlBody } from './html-target'
import type { OutputPayload, OutputTarget, OutputAttemptResult } from './types'

const BUNDLE_README = `# Omniply Article Bundle

This bundle contains a complete, self-contained article package ready for any static site generator.

## Files

| File | Description |
|------|-------------|
| \`article.html\` | Standalone HTML with embedded CSS and relative image paths |
| \`article.md\`   | Markdown version (converted from article HTML) |
| \`metadata.json\`| Machine-readable manifest — title, SEO, citations, diagram info |
| \`images/featured.jpg\` | Featured image (original quality) |
| \`images/diagrams/\` | Mermaid diagrams — both PNG (1200px) and SVG (resolution-independent) |

## Usage

### Hugo / Eleventy / Jekyll
Place \`article.md\` in your \`content/\` folder.
Copy \`images/\` alongside it.
Inject front-matter from \`metadata.json\` as needed.

### Astro / Next.js MDX
Use \`article.md\` as an MDX file.
Reference \`metadata.json\` for frontmatter.

### Standalone HTML
Open \`article.html\` directly in a browser — no server required.

---
Generated by **Omniply** · https://www.omniply.io
`

async function streamToBuffer(readable: NodeJS.ReadableStream): Promise<Buffer> {
  const chunks: Buffer[] = []
  for await (const chunk of readable) {
    chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk as string))
  }
  return Buffer.concat(chunks)
}

function buildManifest(payload: OutputPayload): Record<string, unknown> {
  return {
    title: payload.title,
    slug: payload.slug,
    excerpt: payload.excerpt,
    seo: { title: payload.seoTitle, description: payload.seoDescription },
    primaryKeyword: payload.primaryKeyword,
    disclaimer: payload.disclaimer,
    citations: payload.citations,
    featuredImage: payload.featuredImage
      ? {
          file: 'images/featured.jpg',
          alt: payload.featuredImage.alt,
          width: payload.featuredImage.width,
          height: payload.featuredImage.height,
        }
      : null,
    diagrams: payload.diagrams.map((d) => ({
      position: d.position,
      section: d.sectionTitle,
      caption: d.caption,
      files: {
        png: `images/diagrams/${d.position}.png`,
        svg: `images/diagrams/${d.position}.svg`,
      },
      width: d.width,
      height: d.height,
    })),
    meta: {
      readingTime: payload.meta.readingTime,
      publishedAt: payload.meta.publishedAt?.toISOString() ?? null,
    },
    generatedBy: { tool: 'Omniply', jobId: payload.jobId, version: 'v1' },
  }
}

async function fetchBuffer(url: string): Promise<Buffer> {
  const res = await fetch(url)
  if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status}`)
  return Buffer.from(await res.arrayBuffer())
}

function buildMarkdownArticle(payload: OutputPayload): string {
  // YAML frontmatter
  const fmLines = [
    '---',
    `title: "${payload.title.replace(/"/g, '\\"')}"`,
    `slug: "${payload.slug}"`,
    payload.excerpt ? `excerpt: "${payload.excerpt.replace(/"/g, '\\"')}"` : null,
    `seo_title: "${payload.seoTitle.replace(/"/g, '\\"')}"`,
    `seo_description: "${payload.seoDescription.replace(/"/g, '\\"')}"`,
    payload.primaryKeyword ? `primary_keyword: "${payload.primaryKeyword.replace(/"/g, '\\"')}"` : null,
    payload.meta.readingTime != null ? `reading_time: ${payload.meta.readingTime}` : null,
    payload.meta.publishedAt ? `published_at: "${payload.meta.publishedAt.toISOString()}"` : null,
    payload.featuredImage ? `featured_image: images/featured.jpg` : null,
    '---',
  ].filter(Boolean).join('\n')

  // Featured image as markdown at the top of content
  const featuredImageMd = payload.featuredImage
    ? `![${payload.featuredImage.alt}](images/featured.jpg)\n\n`
    : ''

  // Tier 2 citations appended as a References section
  const referenceCitations = payload.citations.filter(
    (c) => c.link_url && c.source_type !== 'inline',
  )
  const citationsMd =
    referenceCitations.length > 0
      ? `\n\n## References\n\n${referenceCitations
          .map((c, i) => `${i + 1}. [${c.link_title || c.link_url}](${c.link_url})`)
          .join('\n')}`
      : ''

  return `${fmLines}\n\n# ${payload.title}\n\n${featuredImageMd}${payload.bodyMarkdown}${citationsMd}`
}

export class BundleTarget implements OutputTarget {
  name = 'bundle'

  async publish(
    payload: OutputPayload,
    _config: Record<string, unknown>,
    _attemptId: string,
  ): Promise<OutputAttemptResult> {
    const start = Date.now()

    const archive = archiver('zip', { zlib: { level: 9 } })
    const bufferPromise = streamToBuffer(archive)

    // article.html with relative image paths
    archive.append(buildHtmlBody(payload, { relativeImages: true }), { name: 'article.html' })
    // article.md — with YAML frontmatter, featured image, and citations
    archive.append(buildMarkdownArticle(payload), { name: 'article.md' })
    // metadata.json
    archive.append(JSON.stringify(buildManifest(payload), null, 2), { name: 'metadata.json' })
    // README.md
    archive.append(BUNDLE_README, { name: 'README.md' })

    // Featured image
    if (payload.featuredImage) {
      try {
        const imgBuf = await fetchBuffer(payload.featuredImage.cdnUrl)
        archive.append(imgBuf, { name: 'images/featured.jpg' })
      } catch {
        // Non-fatal — skip if download fails
      }
    }

    // Diagrams
    for (const d of payload.diagrams) {
      try {
        const pngBuf = await fetchBuffer(d.cdnUrl)
        archive.append(pngBuf, { name: `images/diagrams/${d.position}.png` })
      } catch {
        // Non-fatal
      }
      archive.append(d.svgContent, { name: `images/diagrams/${d.position}.svg` })
    }

    await archive.finalize()
    const zipBuffer = await bufferPromise

    const s3Key = `exports/${payload.userId}/${payload.jobId}/article.zip`
    const { url } = await uploadBufferWithKey(s3Key, zipBuffer, 'application/zip')

    return {
      success: true,
      resultUrl: url,
      targetRefId: s3Key,
      durationMs: Date.now() - start,
    }
  }
}
